name: reddit_readonly
description: client for reddit read-only REST API
version: 0.2.5

environment:
  sdk: ^3.7.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  test: ^1.21.0
