name: reddit_readonly
description: client for reddit read-only REST API
version: 0.2.4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  all_lint_rules_community: ^0.0.40
  test: ^1.21.0
