name: reddit_readonly
description: client for reddit read-only REST API
version: 0.2.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
